services:
  115transfer:
    image: ghcr.io/dtqeight/115transfer:master
    container_name: 115transfer
    ports:
      - "3698:3698"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - FLASK_DEBUG=false
      - TZ=Asia/Shanghai
      - DATA_DIR=/app/data
      - PYTHONUNBUFFERED=1